// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(CotacaoDbContext))]
    [Migration("20251201083349_Baseline")]
    partial class Baseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Cobertura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorMaximo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorMinimo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Coberturas", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Cotacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Comissao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CorretorId")
                        .HasColumnType("int");

                    b.Property<decimal>("DescontoComercial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DtValidade")
                        .HasColumnType("datetime2");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("PremioComercial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PremioLiquido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PremioTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cotacoes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CotacaoCobertura", b =>
                {
                    b.Property<int>("CotacaoId")
                        .HasColumnType("int");

                    b.Property<int>("CoberturaId")
                        .HasColumnType("int");

                    b.Property<bool>("Contratada")
                        .HasColumnType("bit");

                    b.Property<string>("FranquiaSelecionada")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ImportanciaSegurada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PremioCobertura")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CotacaoId", "CoberturaId");

                    b.ToTable("CotacaoCoberturas", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FatorBonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClasseBonus")
                        .HasColumnType("int");

                    b.Property<decimal>("Fator")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.ToTable("FatorBonus", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FatorFranquia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Fator")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Franquia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("FatorFranquia", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FatorPerfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FaixaIdade")
                        .HasColumnType("int");

                    b.Property<decimal>("Fator")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FatorPerfil", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FatorRegiao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CepFim")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("CepInicio")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal>("Fator")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.ToTable("FatorRegiao", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FatorUtilizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Fator")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("TipoUtilizacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FatorUtilizacao", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal>("CustoServicos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DescontoComercialMaxPercentual")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("IofPercentual")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PercentualComissao")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.ToTable("Produtos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Proponente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CepResidencial")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("CotacaoId")
                        .HasColumnType("int");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DtNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CotacaoId")
                        .IsUnique();

                    b.ToTable("Proponentes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("int");

                    b.Property<int>("AnoModelo")
                        .HasColumnType("int");

                    b.Property<bool>("Blindado")
                        .HasColumnType("bit");

                    b.Property<string>("CepPernoite")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Chassi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoFipeOuVeiculo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CotacaoId")
                        .HasColumnType("int");

                    b.Property<bool>("KitGas")
                        .HasColumnType("bit");

                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoUtilizacao")
                        .HasColumnType("int");

                    b.Property<bool>("ZeroKm")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CotacaoId")
                        .IsUnique();

                    b.ToTable("Veiculos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Cobertura", b =>
                {
                    b.HasOne("Domain.Entities.Produto", null)
                        .WithMany("CoberturasDisponiveis")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.CotacaoCobertura", b =>
                {
                    b.HasOne("Domain.Entities.Cotacao", null)
                        .WithMany("Coberturas")
                        .HasForeignKey("CotacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Proponente", b =>
                {
                    b.HasOne("Domain.Entities.Cotacao", null)
                        .WithOne("Proponente")
                        .HasForeignKey("Domain.Entities.Proponente", "CotacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Veiculo", b =>
                {
                    b.HasOne("Domain.Entities.Cotacao", null)
                        .WithOne("Veiculo")
                        .HasForeignKey("Domain.Entities.Veiculo", "CotacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Cotacao", b =>
                {
                    b.Navigation("Coberturas");

                    b.Navigation("Proponente");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Domain.Entities.Produto", b =>
                {
                    b.Navigation("CoberturasDisponiveis");
                });
#pragma warning restore 612, 618
        }
    }
}
